=== IfremerUnderwater/Matisse/Config/schemas/MatisseParametersDictionnary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="Matisse" xmlns="Matisse">

    <xs:simpleType name="Level" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="user"/>
            <xs:enumeration value="advanced"/>
            <xs:enumeration value="expert"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Type" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="integer"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="bool"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Show" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="line"/>
            <xs:enumeration value="spin"/>
            <xs:enumeration value="combo"/>
            <xs:enumeration value="check"/>
            <xs:enumeration value="table"/>
            <xs:enumeration value="dir"/>
            <xs:enumeration value="file"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Parameter">
        <xs:attribute name="name" type="xs:NCName" use="required"/>
        <xs:attribute name="level" type="Level" use="required"/>
        <xs:attribute name="text" type="xs:string" use="required"/>
        <xs:attribute name="suffix" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="Type" use="required"/>
        <xs:attribute name="size" type="xs:string" use="optional"/>
        <xs:attribute name="range" type="xs:string" use="optional"/>
        <xs:attribute name="precision" type="xs:unsignedByte" use="optional"/>
        <xs:attribute name="formatTemplate" type="xs:string" use="optional"/>
        <xs:attribute name="show" type="Show" use="required"/>
        <xs:attribute name="default" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="ParametersGroup">
        <xs:sequence>
            <xs:element name="Parameter" type="Parameter" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:NCName" use="required"/>
        <xs:attribute name="text" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="Structure">
        <xs:sequence>
            <xs:element name="ParametersGroup" type="ParametersGroup" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
    <xs:complexType name="EnumValue">
        <xs:attribute name="name" type="xs:NCName" use="required"/>
        <xs:attribute name="text" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="Enum">
        <xs:sequence>
            <xs:element name="EnumValue" type="EnumValue" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>

    <xs:element name="MatisseParametersDictionnary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Structures" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Structure" type="Structure" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="publicationTimestamp" type="xs:dateTime" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Enums" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Enum" type="Enum" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- unique constraint not supported in Qt 4.8 -->
        <xs:unique name="uniqueStructureName" >
            <xs:selector xpath="Structure" />
            <xs:field xpath="@name" />
        </xs:unique>
        <xs:unique name="uniqueGroupName" >
            <xs:selector xpath="ParametersGroup" />
            <xs:field xpath="@name" />
        </xs:unique>
        <xs:unique name="uniqueParameterName" >
            <xs:selector xpath="Parameter" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>

</xs:schema>

=== IfremerUnderwater/Matisse/Deploy/config/MatisseParametersDictionnary.xml
<?xml version="1.0" encoding="utf-8"?>
<MatisseParametersDictionnary xmlns="Matisse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Matisse ../schemas/MatisseParametersDictionnary.xsd ">
    <Structures publicationTimestamp="2022-12-15T09:21:42">
        <Structure name="algo_param">
            <ParametersGroup name="general_algo_params">
                <Parameter name="sift_code" level="expert" text="Sift algorithm" type="string" range= "{$SIFT_CODE}" show="combo" default="GPU_sift"/>
                <Parameter name="scale_factor" level="user" text="Image scaling factor" suffix="%" type="double" range="[0,1]" precision="3" show="spin" default="1"/>
                <Parameter name="maxdist_centers" level="expert" text="Research dist (m)" suffix="pixels" type="double" range="]0,inf[" precision="3" show="spin" default="10"/>
                <Parameter name="min_matches" level="advanced" text="Minimum matches" type="integer" range="[4,inf[" show="spin" default="10"/>
                <Parameter name="max_matches" level="advanced" text="Maximum matches" type="integer" range="[4,inf[" show="spin" default="inf"/>
                <Parameter name="First_processed_image" level="user" text="First image index" type="integer" range="[1,inf[" show="spin" default="1"/>
                <Parameter name="Last_processed_image" level="user" text="Last image index" type="integer" range="[1,inf[" show="spin" default="inf"/>
                <Parameter name="step_im" level="user" text="Images step" type="integer" range="[1,inf[" show="spin" default="1"/>
                <Parameter name="force_recompute" level="user" text="Force recompute" type="bool" show="check" default="0"/>
				<Parameter name="force_gpu_usage" level="user" text="Force gpu usage" type="bool" show="check" default="0"/>
            </ParametersGroup>
            <ParametersGroup name="overlap_filtering_params" text="Images overlap handling">
                <Parameter name="disjoint_drawing" level="user" text="Disjoint mosaicking" type="bool" show="check" default="0"/>
                <Parameter name="single_image_output" level="user" text="Single image output type" type="string" range= "{$DRAWING_OUTPUT_TYPE}" show="combo" default="geotiff_only"/>
                <Parameter name="filter_overlap" level="expert" text="Overlap filtering" type="bool" show="check" default="0"/>
                <Parameter name="max_overlap" level="expert" text="Max overlap between 2 images" type="double" range="[0,1]" precision="2" show="spin" default="0.9"/>
                <Parameter name="min_overlap" level="expert" text="Min overlap between 2 images" type="double" range="[0,1]" precision="2" show="spin" default="0.7"/>
		        <Parameter name="do_realtime_mosaicking" level="user" text="Activate realtime mosaicking" type="bool" show="check" default="1"/>
                <Parameter name="use_gpu_with_opencl" level="expert" text="Activate the use of GPU acceleration with OpenCL" type="bool" show="check" default="0"/>
            </ParametersGroup>
            <ParametersGroup name="bundle_adjustment_params" text="Bundle adjustment">
                <Parameter name="MaxIter" level="expert" text="Max iterations in optimization" type="integer" range="]1,inf[" show="spin" default="50"/>
                <Parameter name="max_Roll" level="expert" text="Max roll" type="double" range="[0,inf[" precision="3" show="spin" default="0.1"/>
                <Parameter name="max_Pitch" level="expert" text="Max pitch" type="double" range="[0,inf[" precision="3" show="spin" default="0.1"/>
                <Parameter name="ba_method" level="user" text="Mosaicking method" type="string" range="{$BA_METHOD}" show="combo" default="Nav_only"/>
                <Parameter name="cosmetic_stretch" level="user" text="Color correction" type="bool" show="check" default="0"/>
            </ParametersGroup>
            <ParametersGroup name="blending_displaying_params" text="Blending and display parameters">
                <Parameter name="expo_comp_method" level="expert" text="Exposition comp. method" type="string" range="{$EXPO_COMP_METHOD}" show="combo" default="gain"/>
                <Parameter name="seam_method" level="expert" text="Seaming algorithm" type="string" range="{$SEAM_METHOD}" show="combo" default="gc_color"/>
                <Parameter name="blending_method" level="expert" text="Blending algorithm" type="string" range="{$BLENDING_METHOD}" show="combo" default="multiband"/>
                <Parameter name="no_plot" level="user" text="No plot (just progression bar)" type="bool" show="check" default="1"/>
                <Parameter name="WriteGeoTiff" level="user" text="Write GeoTiff" type="bool" show="check" default="1"/>
                <Parameter name="block_drawing" level="user" text="Block drawing (better mem management)" type="bool" show="check" default="0"/>
                <Parameter name="block_width" level="user" text="Mean block width" type="integer" range="]0,inf[" show="spin" default="7000"/>
                <Parameter name="block_height" level="user" text="Mean block height" type="integer" range="]0,inf[" show="spin" default="7000"/>
            </ParametersGroup>
            <ParametersGroup name="compute_feature" text="Compute Features">
                <Parameter name="describer_method" level="expert" text="Feature algorithm" type="string" range="{$DESCRIBER_METHOD}" show="combo" default="SIFT_ANATOMY"/>
                <Parameter name="describer_preset" level="expert" text="Feature preset" type="string" range="{$DESCRIBER_PRESET}" show="combo" default="ULTRA"/>
            </ParametersGroup>
            <ParametersGroup name="compute_matches" text="Compute Matches">
                <Parameter name="nearest_matching_method" level="expert" text="Matching algorithm" type="string" range="{$NEARESTMATCH_METHOD}" show="combo" default="FASTCASCADEHASHINGL2"/>
                <Parameter name="video_mode_matching" level="advanced" text="Transect Matching Im Nb" type="integer" range="[2,100]" show="spin" default="8"/>
				<Parameter name="video_mode_matching_enable" level="advanced" text="Transect Mode" type="bool" show="check" default="0"/>
                <Parameter name="nav_based_matching_enable" level="advanced" text="Nav based matching" type="bool" show="check" default="1"/>
                <Parameter name="nav_based_matching_max_dist" level="expert" text="Nav matching max dist" type="double" range="]0.1,20]" precision="2" show="spin" default="10.0"/>
				<Parameter name="guided_matching" level="expert" text="Guided Matching based on 2-views Geometry" type="bool" show="check" default="1"/>
            </ParametersGroup>
            <ParametersGroup name="DensifyPointCloud" text="Densify Point Cloud">
                <Parameter name="resolution_level" level="expert" text="Resolution level divider" type="integer" range="[1,10]" show="spin" default="2"/>
                <Parameter name="number_views_fuse" level="expert" text="Number Views Fuse" type="integer" range="[2,10]" show="spin" default="3"/>
            </ParametersGroup>
            <ParametersGroup name="ReconstructMesh" text="Reconstruct Mesh">
                <Parameter name="decimate_factor" level="expert" text="Decimation Factor" type="double" range="]0,1]" precision="2" show="spin" default="1.0"/>
            </ParametersGroup>
            <ParametersGroup name="TexReCon" text="Texture Mesh">
                <Parameter name="keep_unseen_faces" level="expert" text="Keep Unseen Faces" type="bool" show="check" default="0"/>
            </ParametersGroup>
        </Structure>
        <Structure name="vehic_param">
            <ParametersGroup name="vehicle_params">
                <Parameter name="reproj_std" level="advanced" text="Retroprojection std (in px)" type="double" range="]0,inf[" precision="3" show="spin" default="1"/>
                <Parameter name="X_std" level="advanced" text="X axis std (m)" type="double" range="]0,inf[" precision="3" show="spin" default="3"/>
                <Parameter name="Y_std" level="advanced" text="Y axis std (m)" type="double" range="]0,inf[" precision="3" show="spin" default="3"/>
                <Parameter name="alt_std" level="advanced" text="Altitude std (m)" type="double" range="]0,inf[" precision="3" show="spin" default="0.8"/>
				<Parameter name="depth_std" level="advanced" text="depth std (m)" type="double" range="]0,inf[" precision="3" show="spin" default="0.5"/>
                <Parameter name="Roll_std" level="advanced" text="roll std (rad)" type="double" range="]0,inf[" precision="3" show="spin" default="0.01"/>
                <Parameter name="Pitch_std" level="advanced" text="pitch std (rad)" type="double" range="]0,inf[" precision="3" show="spin" default="0.01"/>
                <Parameter name="Yaw_std" level="advanced" text="heading std (rad)" type="double" range="]0,inf[" precision="3" show="spin" default="0.1"/>
            </ParametersGroup>
        </Structure>
        <Structure name="cam_param">
            <ParametersGroup name="advanced_camera_params" text="Camera parameters">
                <Parameter name="K" level="advanced" text="Camera calibration matrix" type="double" size="(3,3)" range="]-inf,inf[" precision="2" formatTemplate="9999.99" show="table" default="1440; 0; 960; 0; 1440; 540; 0; 0; 1"/>
                <Parameter name="V_Pose_C" level="advanced" text="Cam/IMU rel. position" type="double" size="(6,1)" range="]-inf,inf[" precision="3" formatTemplate="-9.999" show="table" default="-1.1000; 0.2500; -0.1500; 0; 0; -1.5708"/>
		        <Parameter name="still_camera_port" level="user" text="Still camera TCP port" type="integer" range="[1000,99999]" show="spin" default="5600"/>
                <Parameter name="still_camera_address" level="user" text="Still camera address" type="string" show="line" default="192.168.1.104"/>
