=== IfremerUnderwater/Matisse/main/qt/xml/models/parameters/Parameters_V1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mosaic_settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fileDescriptor"/>
        <xs:element ref="algo_param"/>
        <xs:element ref="cam_param"/>
        <xs:element ref="dataset_param"/>
        <xs:element ref="vehic_param"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fileDescriptor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="modelVersion"/>
        <xs:element ref="name"/>
        <xs:element ref="date"/>
        <xs:element ref="author"/>
        <xs:element ref="comments"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="modelVersion" type="xs:decimal"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="comments" type="xs:string"/>
  <xs:element name="algo_param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sift_code"/>
        <xs:element ref="scale_factor"/>
        <xs:element ref="maxdist_centers"/>
        <xs:element ref="min_matches"/>
        <xs:element ref="max_matches"/>
        <xs:element ref="First_processed_image"/>
        <xs:element ref="Last_processed_image"/>
        <xs:element ref="step_im"/>
        <xs:element ref="filter_overlap"/>
        <xs:element ref="max_overlap"/>
        <xs:element ref="min_overlap"/>
        <xs:element ref="MaxIter"/>
        <xs:element ref="MaxRoll"/>
        <xs:element ref="max_Pitch"/>
        <xs:element ref="ba_method"/>
        <xs:element ref="cosmetic_strech"/>
        <xs:element ref="expo_comp_method"/>
        <xs:element ref="seam_method"/>
        <xs:element ref="blending_method"/>
        <xs:element ref="no_plot"/>
        <xs:element ref="WriteGeoTiff"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sift_code" type="xs:NCName"/>
  <xs:element name="scale_factor" type="xs:string"/>
  <xs:element name="maxdist_centers" type="xs:string"/>
  <xs:element name="min_matches" type="xs:integer"/>
  <xs:element name="max_matches" type="xs:NCName"/>
  <xs:element name="First_processed_image" type="xs:integer"/>
  <xs:element name="Last_processed_image" type="xs:NCName"/>
  <xs:element name="step_im" type="xs:integer"/>
  <xs:element name="filter_overlap" type="xs:boolean"/>
  <xs:element name="max_overlap" type="xs:string"/>
  <xs:element name="min_overlap" type="xs:string"/>
  <xs:element name="MaxIter" type="xs:integer"/>
  <xs:element name="MaxRoll" type="xs:NCName"/>
  <xs:element name="max_Pitch" type="xs:NCName"/>
  <xs:element name="ba_method" type="xs:NCName"/>
  <xs:element name="cosmetic_strech" type="xs:boolean"/>
  <xs:element name="expo_comp_method" type="xs:NCName"/>
  <xs:element name="seam_method" type="xs:NCName"/>
  <xs:element name="blending_method" type="xs:NCName"/>
  <xs:element name="no_plot" type="xs:boolean"/>
  <xs:element name="WriteGeoTiff" type="xs:boolean"/>
  <xs:element name="cam_param">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="K"/>
        <xs:element ref="V_Pose_C"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="K" type="xs:string"/>
  <xs:element name="V_Pose_C" type="xs:string"/>
  <xs:element name="dataset_param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dataset_dir"/>
        <xs:element ref="output_dir"/>
        <xs:element ref="output_filename"/>
        <xs:element ref="navFile"/>
        <xs:element ref="utm_zone"/>
        <xs:element ref="utm_hemisphere"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataset_dir" type="xs:string"/>
  <xs:element name="output_dir" type="xs:string"/>
  <xs:element name="navFile" type="xs:NCName"/>
  <xs:element name="utm_zone" type="xs:integer"/>
  <xs:element name="utm_hemisphere" type="xs:NCName"/>
  <xs:element name="vehic_param">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reproj_std"/>
        <xs:element ref="X_std"/>
        <xs:element ref="Y_std"/>
        <xs:element ref="alt_std"/>
        <xs:element ref="Roll_std"/>
        <xs:element ref="Pitch_std"/>
        <xs:element ref="Yaw_std"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reproj_std" type="xs:string"/>
  <xs:element name="X_std" type="xs:string"/>
  <xs:element name="Y_std" type="xs:string"/>
  <xs:element name="alt_std" type="xs:string"/>
  <xs:element name="Roll_std" type="xs:string"/>
  <xs:element name="Pitch_std" type="xs:string"/>
  <xs:element name="Yaw_std" type="xs:string"/>
</xs:schema>

=== IfremerUnderwater/Matisse/main/qt/xml_backup/parameters/V1.0/Parametres_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<mosaic_settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../models/parameters/Parameters_V1.0.xsd"> 

<fileDescriptor>
<modelVersion>V1.0</modelVersion>
<name>Parametres 1</name>
<date>25/02/2014</date>
<author>TCA</author>
<comments>Test</comments>
</fileDescriptor>

<algo_param>
<sift_code>GPU_sift</sift_code>
<scale_factor>1,000</scale_factor>
<maxdist_centers>10,000</maxdist_centers>
<min_matches>10</min_matches>
<max_matches>inf</max_matches>
<First_processed_image>2</First_processed_image>
<Last_processed_image>inf</Last_processed_image>
<step_im>2</step_im>

<!--Filtering overlap parameters-->
<filter_overlap>false</filter_overlap>
<max_overlap>0,900</max_overlap>
<min_overlap>0,700</min_overlap>

<!--Bundle adjustment parameters-->
<MaxIter>300</MaxIter>
<MaxRoll>inf</MaxRoll>
<max_Pitch>inf</max_Pitch>
<ba_method>Ferrer_2008_with_nav</ba_method>
<cosmetic_strech>true</cosmetic_strech>

<!--Blending and displaying parameters-->
<expo_comp_method>gain</expo_comp_method>
<seam_method>gc_color</seam_method>
<blending_method>multiband</blending_method>
<no_plot>false</no_plot>
<WriteGeoTiff>true</WriteGeoTiff>

</algo_param>

<cam_param>
<K>1; 2; 3</K>
<K>4; 5; 6</K>
<K>7; 8; 9</K>
<V_Pose_C>1; 2; 3; 4; 5; 6</V_Pose_C>

</cam_param>

<dataset_param>
<dataset_dir>./</dataset_dir>
<output_dir>./Geotiff_data</output_dir>
<output_file>OutputFile.tiff</output_file>
<navFile>navFile_mv.txt</navFile>
<utm_zone>31</utm_zone>
<utm_hemisphere>N</utm_hemisphere>

</dataset_param>

<vehic_param>
<reproj_std>1,000</reproj_std>
<X_std>2,000</X_std>
<Y_std>2,000</Y_std>
<alt_std>2,000</alt_std>
<Roll_std>0,010</Roll_std>
<Pitch_std>0,010</Pitch_std>
<Yaw_std>0,010</Yaw_std>

</vehic_param>

</mosaic_settings>

=== IfremerUnderwater/Matisse/main/qt/xml/users/parameters/V1.0/working.xml
<?xml version="1.0" encoding="UTF-8"?>

<mosaic_settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../models/parameters/Parameters_V1.0.xsd">

<fileDescriptor>
</fileDescriptor>

<algo_param>
<sift_code>GPU_sift</sift_code>
<scale_factor>0,100</scale_factor>
<maxdist_centers>10,000</maxdist_centers>
<min_matches>8</min_matches>
<max_matches>inf</max_matches>
<First_processed_image>1</First_processed_image>
<Last_processed_image>10</Last_processed_image>
<step_im>1</step_im>

<!--Filtering overlap parameters-->
<filter_overlap>false</filter_overlap>
<max_overlap>0,900</max_overlap>
<min_overlap>0,700</min_overlap>

<!--Bundle adjustment parameters-->
<MaxIter>99</MaxIter>
<MaxRoll>0</MaxRoll>
<max_Pitch>0</max_Pitch>
<ba_method>Robust_2D_with_nav</ba_method>
<cosmetic_strech>true</cosmetic_strech>

<!--Blending and displaying parameters-->
<expo_comp_method>gain</expo_comp_method>
<seam_method>gc_color</seam_method>
<blending_method>multiband</blending_method>
<no_plot>false</no_plot>
<WriteGeoTiff>true</WriteGeoTiff>

</algo_param>

<cam_param>
<K>5560;0;1960;0;5560;1440;0;0;1</K>
<V_Pose_C>0.45;0.35;-1.07;0;0;-1.6</V_Pose_C>

</cam_param>

<dataset_param>
<relative_path>false</relative_path>
<dataset_dir>D:\DATA\MOSAIC_DATASETS\Morph\Vortex-day5\CanonG9Corr</dataset_dir>
<output_dir>D:\DATA\MOSAIC_DATASETS\Morph\Vortex-day5\CanonG9Corr\Geotiff_data</output_dir>
<output_filename>MosaicOut.tiff</output_filename>
<navFile>iPhoto.dim2</navFile>
<utm_zone>31</utm_zone>
<utm_hemisphere>N</utm_hemisphere>

</dataset_param>

<vehic_param>
<reproj_std>1,000</reproj_std>
<X_std>2,000</X_std>
<Y_std>2,000</Y_std>
<alt_std>2,000</alt_std>
<Roll_std>0,010</Roll_std>
<Pitch_std>0,010</Pitch_std>
<Yaw_std>0,010</Yaw_std>

</vehic_param>

</mosaic_settings>

=== IfremerUnderwater/Matisse/Config/xml/users/parameters/V1.0/nex.xml
<?xml version="1.0" encoding="UTF-8"?>

<mosaic_settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../models/parameters/Parameters_V1.0.xsd">

<fileDescriptor>
</fileDescriptor>

<algo_param>
<sift_code>GPUsift</sift_code>
<scale_factor>1,000</scale_factor>
<maxdist_centers>8,000</maxdist_centers>
<min_matches>12</min_matches>
<max_matches>10000</max_matches>
<First_processed_image>1</First_processed_image>
<Last_processed_image>10</Last_processed_image>
<step_im>1</step_im>

<!--Filtering overlap parameters-->
<filter_overlap>false</filter_overlap>
<max_overlap>0,900</max_overlap>
<min_overlap>0,700</min_overlap>

<!--Bundle adjustment parameters-->
<MaxIter>40</MaxIter>
<max_Roll>inf</max_Roll>
<max_Pitch>inf</max_Pitch>
<ba_method>Robust_2D_with_nav</ba_method>
<cosmetic_stretch>true</cosmetic_stretch>

<!--Blending and displaying parameters-->
<expo_comp_method>gain</expo_comp_method>
<seam_method>gc_color</seam_method>
<blending_method>multiband</blending_method>
<no_plot>false</no_plot>
<WriteGeoTiff>true</WriteGeoTiff>
<block_drawing>true</block_drawing>
<block_width>7000</block_width>
<block_height>7000</block_height>

</algo_param>

<cam_param>
<K>540.6770;0;199.9878;0;539.5830;143.9180;0;0;1</K>
<V_Pose_C>-1.1;0.25;-0.15;0;0;-1.5708</V_Pose_C>

</cam_param>

<dataset_param>
<dataset_dir>D:\DATA\MOSAIC_DATASETS\ROBOMOS\27_10_2010-AGA\Resize_01</dataset_dir>
<output_dir>./Geotiff_data</output_dir>
<output_filename>MosaicOutColorCorr.tiff</output_filename>
<navFile>navFile_mv_small_profile2.txt</navFile>
<utm_zone>31</utm_zone>
<utm_hemisphere>N</utm_hemisphere>

</dataset_param>

<vehic_param>
<reproj_std>10,000</reproj_std>
<X_std>5,000</X_std>
<Y_std>5,000</Y_std>
<alt_std>0,800</alt_std>
<Roll_std>0,010</Roll_std>
<Pitch_std>0,010</Pitch_std>
<Yaw_std>0,100</Yaw_std>

</vehic_param>

</mosaic_settings>
